#!/bin/bash

curdir=$(pwd)
directory=$1
script=$2
argument=$3

function prepend() { while read line; do echo "${1}${line}"; done; }

#Determine page that will be edited
   #if ~/default_page exists, cd to its content
if [ -f "$HOME/.defaultpage" ]; then
    siteRoot=$(cat $HOME/.defaultpage)
fi


cd /home/bitnami/devenv-scripts
source _util.bash
#If current directory contains a file named .deploy, source it
if [ -f ".dev" ]; then
    source .dev
elif [ -f "$siteRoot/.dev" ]; then
    source $siteRoot/.dev
else
    devSiteUrl="${On_Red}NO SITE SELECTED${NC}";
fi

#If current directory contains a file named .deploy, source it
if [ -f ".deploy" ]; then
    source .deploy
elif [ -f "$siteRoot/.deploy" ]; then
    source $siteRoot/.deploy
fi

printf "[[ $devSiteUrl ]]";

if [ -z "$directory" ]; then
    echo ""
        echo ""

    echo "dev $directory"
    ls -1 | grep -v "^_" | sed 's/\.[^.]*$//' | while read -r directory; do
        echo -e "  $directory"
    ls -1 $directory | grep -v "^_" | sed 's/\.[^.]*$//' | while read -r cmd; do
        echo -ne "$cmd ${Gray}_"$(  sed -n '2p' $directory/$cmd.bash  | sed $'\ts/^.\{2\}//')${NC} | column -t -s "_" -o " " | prepend "    "
      done
    done
        printf "\nUsage: dev [category] [action]"
        printf "${Gray}\nExample: dev db pull${NC}"; echo

    exit 0
#if script is --help, do the same as above but for each file in $directory, excluding files starting with _
elif [ -z "$script" ]; then
    echo "dev $directory"
    ls -1 $directory | grep -v "^_" | sed 's/\.[^.]*$//' | while read -r cmd; do
        echo -ne "$cmd ${Gray}_"$(  sed -n '2p' $directory/$cmd.bash  | sed $'\ts/^.\{2\}//')${NC} | column -t -s "_" -o " " | prepend "    "
      
    done
    exit 0
fi

#If $script is not empty, run the script in $directory
if [ ! -z "$script" ]; then
    if [ -f "$directory/$script.bash" ]; then
        cd $siteRoot
        set -e
        source /home/bitnami/devenv-scripts/$directory/$script.bash $argument
    else
        echo "Error: $script not found"
        exit 1
    fi
fi

cd $curdir

